// This file is automatically generated - edits will be lost!

'use server';

/**
 * @fileOverview Suggests optimal workspaces based on predicted ambient sound levels and crowd levels.
 *
 * - suggestOptimalWorkspace - A function that suggests optimal workspaces.
 * - SuggestOptimalWorkspaceInput - The input type for the suggestOptimalWorkspace function.
 * - SuggestOptimalWorkspaceOutput - The return type for the suggestOptimalWorkspace function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestOptimalWorkspaceInputSchema = z.object({
  timeOfDay: z.string().describe('The time of day (e.g., morning, afternoon, evening).'),
  dayOfWeek: z.string().describe('The day of the week (e.g., Monday, Tuesday, Wednesday).'),
  workspacePreferences: z.string().describe('Any specific workspace preferences the user has (e.g., quiet area, near window).'),
});
export type SuggestOptimalWorkspaceInput = z.infer<typeof SuggestOptimalWorkspaceInputSchema>;

const SuggestOptimalWorkspaceOutputSchema = z.object({
  suggestedWorkspace: z.string().describe('The suggested optimal workspace based on predicted sound and crowd levels.'),
  reasoning: z.string().describe('The reasoning behind the workspace suggestion.'),
});
export type SuggestOptimalWorkspaceOutput = z.infer<typeof SuggestOptimalWorkspaceOutputSchema>;

export async function suggestOptimalWorkspace(input: SuggestOptimalWorkspaceInput): Promise<SuggestOptimalWorkspaceOutput> {
  return suggestOptimalWorkspaceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestOptimalWorkspacePrompt',
  input: {schema: SuggestOptimalWorkspaceInputSchema},
  output: {schema: SuggestOptimalWorkspaceOutputSchema},
  prompt: `You are an AI assistant designed to suggest the best workspace for a user based on the time of day, day of week, and their preferences.

  Consider factors such as predicted ambient sound levels and crowd levels to maximize focus and productivity.

  Time of Day: {{{timeOfDay}}}
  Day of Week: {{{dayOfWeek}}}
  User Preferences: {{{workspacePreferences}}}

  Suggest an optimal workspace and explain your reasoning.`, 
});

const suggestOptimalWorkspaceFlow = ai.defineFlow(
  {
    name: 'suggestOptimalWorkspaceFlow',
    inputSchema: SuggestOptimalWorkspaceInputSchema,
    outputSchema: SuggestOptimalWorkspaceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
