// This file is automatically generated - edits will be lost!

// Make sure to fill in your Firebase project configuration
const firebaseConfig = {
  apiKey: "AIzaSyA9fSGzL2hAswup_MvQ0PcJbm2JwBq_rUs",
  authDomain: "studio-1600078381-a8599.firebaseapp.com",
  projectId: "studio-1600078381-a8599",
  storageBucket: "studio-1600078381-a8599.firebasestorage.app",
  messagingSenderId: "485959148106",
  appId: "1:485959148106:web:3d48686c11b2c188013cb3"
};